apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups: ["opentofu.krateo.io"]
    resources: ["tfconnectors"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  
  - apiGroups: ["opentofu.krateo.io"]
    resources: ["tfconnectors/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: ["opentofu.krateo.io"]
    resources: ["workspaces"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  
  - apiGroups: ["opentofu.krateo.io"]
    resources: ["workspaces/status"]
    verbs: ["get", "patch", "update"]
  
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]