apiVersion: opentofu.krateo.io/v1alpha1
kind: Workspace
metadata:
  name: workspace-sample-1
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  deletionPolicy: Delete
  tfConnectorRef:
    name: tfconfig-sample
    namespace: default
  workspace:
    # This is the remote repository that will be used to create the workspace. 
    module: "https://github.com/matteogastaldello/opentofu-example.git"
